# Generated by Django 4.0.3 on 2022-08-16 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_alter_notebooks_photo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebooks',
            name='ordered_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notebooks',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notebooks',
            name='photo_name',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
