# Generated by Django 4.0.3 on 2022-08-16 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_notebooks_ordered_by_notebooks_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebooks',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
