# Generated by Django 4.0.3 on 2022-08-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_notebook_articl_tocard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='photo_name',
            field=models.FilePathField(default=None),
        ),
    ]
