# Generated by Django 4.0.3 on 2022-08-16 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_notebook_photo_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook',
            old_name='photo_name',
            new_name='photo_path',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='ordered_by',
        ),
    ]
