# Generated by Django 4.0.3 on 2022-08-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_photo_name_notebook_photo_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('power', models.CharField(max_length=5)),
                ('num_of_programms', models.CharField(max_length=10)),
                ('volume', models.CharField(max_length=10)),
                ('dry', models.CharField(max_length=10)),
                ('photo_path', models.CharField(max_length=50)),
                ('rating', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('articl', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('diag', models.CharField(max_length=5)),
                ('processor', models.CharField(max_length=10)),
                ('memory', models.CharField(max_length=10)),
                ('disk_volume', models.CharField(max_length=10)),
                ('photo_path', models.CharField(max_length=50)),
                ('rating', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('articl', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('diag', models.CharField(max_length=5)),
                ('smart', models.BooleanField()),
                ('photo_path', models.CharField(max_length=50)),
                ('rating', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('articl', models.IntegerField(default=0)),
            ],
        ),
    ]
